name: CI/CD for Python DevOps Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-statics-type-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Display python version and location
        run: |
          python --version
          which python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
        
      - name: Linting and format check
        run: |
          black --check .
          ruff check .

      - name: Static type check
        run: |
          mypy src/
        
      - name: Security check
        run: |
          bandit -c pyproject.toml -r .
        

  run-tests:
    
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.10', '3.9', '3.12']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '${{ matrix.python-version }}'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"

    - name: Run tests with pytest
      run: |
          pytest tests/
  
  release:
    needs: [lint-statics-type-test, run-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Release
        run: echo "Release"

     
          
          
